from enum import IntEnum

class InfoCode(IntEnum):
    # System Info (9000-9999)
    SYSTEM_GRPC_START_SUCCESS = 9901
    SYSTEM_GRPC_STOP_SUCCESS = 9902
    SYSTEM_DETECTION_STARTED_SUCCESS = 9903
    SYSTEM_DETECTION_STOPPED_SUCCESS = 9904